baseURL = 'https://giveupenglish.org'
title = 'GIVE UP ENGLISH'
theme = 'blank'
uglyurls = true

[Params]
  mainSections = ['episodes']
  baseURL = 'https://giveupenglish.org'
  logo = 'https://giveupenglish.org/images/podcast.jpg'
  author = 'QUITTER'
  email = 'jason@giveupenglish.com'
  podcastLanguage = 'en-us'
  podcastGenerator = 'giveupenglish.org'
  itunesCategory1 = 'Society &amp; Culture'
  itunesCategory2 = 'Personal Journals'
  podcastLicense = 'CC-BY-SA'
  podcastTitle = 'GIVE UP ENGLISH'
  podcastArt = 'https://giveupenglish.org/images/podcast.jpg'
  podcastSubtitle = 'Sorry, I would like to give up...🤪'
  podcastSummary = '''
  Sorry, I would like to give up English as it is just too difficult for me...🤪<br /><br />
  <a href="https://giveupenglish.org">giveupenglish.org</a>
  '''

[outputFormats]
  [outputFormats.feed]
    baseName = 'feed'
    mediaType = 'application/rss+xml'
    isPlainText = true

[outputs]
  home = ['html', 'feed']
